year = 1650
place = 'Milan'

varii = \
    {
        1: 'NHMPABNHMGHBG',
        2: 'EBGHBGBEOCACABCAGBEOIC',
        3: 'OCOGHGOCOCOGHGOCA',
        4: 'OCADHIEIEFGEBGBEIEICAICAGBGMEBHCABCA',
        5: 'GAIHBGHAIHBGEBHOICEBGABEBHAICFBGABEDFDHAG',
        6: 'ABCAFGABFGABACACAGFCICABCAIBCA',
        7: 'FGABFGABADCAGFCABCABCA',
        8: 'OCABGBGOLCABCALCA',
        9: 'GBEDGBGBEDHZRZHBG',
        10: 'OGHBHGAGOLOLCOLCOLCOL',
        11: 'EBGBGBGEOIEOIEOIE',
        12: 'ABCABCACICAICDABCABCA',
        13: 'ACFABCABCDFGABACAFGEFIDCABCAFGEFABCA',
        14: 'OLCAOHGOLCAHGALCA',
        15: 'GBGBEIECICAIC'
    }